filetype off

" ################################################
" Vundle
" ################################################
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" ################################################
" Misc
" ################################################
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'valloric/youcompleteme'
Plugin 'mileszs/ack.vim'
Plugin 'morhetz/gruvbox'
Plugin 'fatih/vim-go'
Plugin 'itchyny/lightline.vim'

" Plugin 'pangloss/vim-javascript'
" Plugin 'mxw/vim-jsx'
" Plugin 'leafgarland/typescript-vim'
" Plugin 'peitalin/vim-jsx-typescript'
" Plugin 'alvan/vim-closetag'
" Plugin 'prettier/vim-prettier', {'do': 'npm install'}
call vundle#end()
filetype plugin indent on

" Regular configurations
set relativenumber
set cursorline
set nocompatible
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab 
set autoindent
set wildmenu
set noswapfile
syntax on
set laststatus=2
let &t_ut=''
set background=dark
colorscheme gruvbox


" easer movement no wrapped lines
nnoremap j gj
nnoremap k gk

" leader mapping
let mapleader = ','

" Nerdtree
nmap <C-b> :NERDTreeToggle<CR>

" Easier split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" You Complete me
nnoremap <Leader>gd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <Leader>gt :YcmCompleter GoTo<CR>
nnoremap <Leader>rn :YcmCompleter RefactorRename 
nnoremap <Leader>fi :YcmCompleter FixIt<CR>


" Ack
nnoremap <Leader>s :Ack --ignore-dir={build,dist,node_modules}   ./<Left><Left><Left><Left>

" Easy search
map <space> /

" Go-lang
au FileType go set noexpandtab
au FileType go set shiftwidth=4
au FileType go set softtabstop=4
au FileType go set tabstop=4
au FileType go nnoremap <Leader>gec :GoErrCheck<CR>
let g:go_fmt_command = "goimports"



" We dont want to se pyc files i the tree
let NERDTreeIgnore = ['\.pyc$', '__pycache__$']
