filetype off

" ################################################
" Vundle
" ################################################
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" ################################################
" Misc
" ################################################
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'jiangmiao/auto-pairs'
Plugin 'valloric/youcompleteme'
Plugin 'morhetz/gruvbox'
Plugin 'fatih/vim-go'
Plugin 'itchyny/lightline.vim'
Plugin 'junegunn/fzf.vim'

Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'alvan/vim-closetag'
Plugin 'leafgarland/typescript-vim'
Plugin 'peitalin/vim-jsx-typescript'
Plugin 'mhartington/oceanic-next'


call vundle#end()
filetype plugin indent on

" Regular configurations
set tabstop=2
set softtabstop=2
set shiftwidth=2
set laststatus=2
set relativenumber
set cursorline
set nocompatible
set expandtab 
set autoindent
set wildmenu
set noswapfile
let &t_ut=''
set background=dark
set noruler
set noshowmode
syntax on
colorscheme OceanicNext


" sane movement on wrapped line
nnoremap j gj
nnoremap k gk

" move lines in visual, insert and normal
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
nnoremap <C-K> :m .-2<CR>==
nnoremap <C-J> :m .+1<CR>==
inoremap <C-k> <Esc>:m .-2<CR>==gi
inoremap <C-j> <Esc>:m .+1<CR>==gi

" leader mapping
let mapleader = ','

" Nerdtree
nmap <C-b> :NERDTreeToggle<CR>

" You Complete me
nnoremap <Leader>gd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <Leader>gt :YcmCompleter GoTo<CR>
nnoremap <Leader>rn :YcmCompleter RefactorRename 
nnoremap <Leader>fi :YcmCompleter FixIt<CR>

" FZF
" Search files in project
nnoremap <C-P> :Files<CR>
nnoremap <Leader>s :Ag 



" Easy search
map <space> /

" Go-lang
au FileType go set noexpandtab
au FileType go set shiftwidth=4
au FileType go set softtabstop=4
au FileType go set tabstop=4
au FileType go nnoremap <Leader>gec :GoErrCheck<CR>
let g:go_fmt_command = "goimports"



" We dont want to se pyc files i the tree
let NERDTreeIgnore = ['\.pyc$', '__pycache__$']

let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.erb,*.js,*.tsx"
let g:closetag_xhtml_filenames = '*.xhtml,*.js,*.tsx'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
