source ~/Documents/scripts/antigen.zsh
antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply

export PATH="$PATH:$HOME/go/bin"


export EDITOR=vim
